### ISSUE TITLE
Vibrate on tap (-/+)

### ISSUE THREAD

**Issue by n-apps** [n-apps/ScoreCounter#24]

**Comment by vabene1111** [comment]
i have implemented this feature including a setting to turn it off and on. I have set the default to vibrate to make people aware of the existence of this feature but it might annoy some people. 

What do you like as a default for this setting, on or off ?

**Comment by n-apps** [comment]
Is this a "light" vibrate (Haptic Feedback)? I'm not sure this is correct, but I hope you will get what I mean by this :) Reading minds 😺 

> What do you like as a default for this setting, on or off ?
Definitely on.

**Comment by vabene1111** [comment]
I honestly did not look into vibration intensity but i set it to 80ms which feels very short and light.

i will see if its possible to decrease intensity as well but i would say it feels pretty good overall.
