### ISSUE TITLE
Implement dark mode (Android 10+)

### ISSUE THREAD

**Issue by n-apps** [n-apps/ScoreCounter#35]
https://arturdryomov.online/posts/midnight-in-android-themes/

**Comment by vabene1111** [comment]
maybe, when implementing this feature, one could also slightly change the dark mode colors to better fit with the default dark color theme (e.g. instead of black some grey-ish colors and so on). 

I am no design expert and the current version is fine, but maybe it looks better

**Comment by n-apps** [comment]
Definitely will update dark mode colors. Thanks for suggestion 😉

**Comment by vabene1111** [comment]
Currently the new dark colors look like this, the colors.xml is cleaned up a little so the same ressource names are used for dark and ligth theme (makes changes much easier).

<img width="190" alt="2019-09-24_15-04_Android_Emulator_-_Pixel_3_API_295554" src="https://user-images.githubusercontent.com/6819595/65514499-b35f0b80-dedd-11e9-94fb-48ec46dc29ec.png">
<img width="190" alt="2019-09-24_15-08_Android_Emulator_-_Pixel_3_API_295554 (2)" src="https://user-images.githubusercontent.com/6819595/65514501-b35f0b80-dedd-11e9-86c6-a06e06110dab.png">
<img width="190" alt="2019-09-24_15-08_Android_Emulator_-_Pixel_3_API_295554" src="https://user-images.githubusercontent.com/6819595/65514502-b2c67500-dedd-11e9-9dd0-4cb6adcd7fd3.png">

**Comment by n-apps** [comment]
I think, better to use the system settings on Android ≥ Q and hide the switch

**Comment by vabene1111** [comment]
ok then i will just implement a little piece of hiding code, i prefer this way as well!
