### ISSUE TITLE
[Edit counter screen] Save button overlaps inputs

### ISSUE THREAD

**Issue by n-apps** [n-apps/ScoreCounter#37]
Both portrait and landscape modes 🙈 
![image](https://user-images.githubusercontent.com/16646251/64695487-f0baa680-d4a4-11e9-8696-25f15b4a6157.png)

**Comment by vabene1111** [comment]
will be fixed in a PR that i will submit in a few days

**Comment by n-apps** [comment]
Released in 5.3.0
