### ISSUE TITLE
"Who goes first?" option in the counters screen

### ISSUE THREAD

**Issue by n-apps** [n-apps/ScoreCounter#49]
Useful in determining player orders or picking teams

Inspired by users requests and https://play.google.com/store/apps/details?id=com.tendadigital.chwaziApp

> Is there anyway to include a coin toss head or tail for who goes first? Or could it take the names of the players and pick one out randomly in an animation?

**Comment by gjeuken** [comment]
Maybe this code helps:
https://github.com/jbellue/elektu

**Comment by n-apps** [comment]
As a utility solution, I'm leaning towards an option in counters menu which will show a popup modal with random counter name and color.

**Comment by n-apps** [comment]
Added the [link to the web version](https://jbellue.github.io/elektu/ ) inside the options menu for now.
