### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by n-apps** [n-apps/ScoreCounter#5]

**Comment by makmm** [comment]
Hello! I would like to contribute with this. How can I get started? I have no experience in Android development, btw.

**Comment by asicoderpower** [comment]
Hello! I have experience in Android development, and I my mother thongue is spanish 👍 
I would like to contribute to translate the app, how can I help you? 
I am waiting to hear from you :D

**Comment by n-apps** [comment]
Thank you for volunteering to do a translation! If you're familiar with Android development and git there are simple steps: 

1.  Follow the instructions at http://help.github.com/fork-a-repo/ to fork https://github.com/n-apps/ScoreCounter
2. Create a subdirectory of "res" named "values-es".
3. Copy res/values/strings.xml to the directory you just created. Apply translations as described above - making sure to delete any entries which you don't need to translate.
4. Change the files on your local machine then push them back up to your fork (see "Push Commits" in the fork-a-repo document linked above)
5. Send me a "pull request" from your repo - see instructions [here](http://help.github.com/send-pull-requests/)

If you've never used git, download [this file](https://raw.githubusercontent.com/n-apps/ScoreCounter/master/app/src/main/res/values/strings.xml) and edit it using the text editor of your choice (notepad etc...) and just email your modified files to me. 

If you have questions I'm happy to help. If you decide to just email the files that is fine too.

My English isn't perfect, so the English texts could contain wrong translations. Feel free to contact me or fix it with Pull Request 😉

**Comment by asicoderpower** [comment]
Ok, in some minutes it will be done. I am first going to translate everything to spanish and send the pull request. Then, I will check the english file.
Let's go!

**Comment by asicoderpower** [comment]
Hi! I've already made the spanish translation's pull request. Tell me if there is any problem @n-apps 👍 
Now, I am going to check the english strings.xml file, and if there's some mistake or message not expressed in the most understandable way, I will fix it without problems
