### ISSUE TITLE
Large Layout broken in Landscape Mode

### ISSUE THREAD

**Issue by vabene1111** [n-apps/ScoreCounter#67]
when switching to landscape mode the large layout is broken. The emulator kinda crashes my phone just does not show the score part and switches back to portrait when klicking the edit buttons. 

i guess there are the following options
- disable landscape switching as it does not have any value for the app anyway (until #59 is done)
- enable scrolling for large counters in landscape
- always show small + scrolling in landscape mode 

![image](https://user-images.githubusercontent.com/6819595/92750513-6b075a80-f387-11ea-94ed-64599688d547.png)

**Comment by n-apps** [comment]
I'm voting for disable landscape switching

**Comment by vabene1111** [comment]
ok i have done some further testing, landscape mode breaks a lot of things and i dont see any reason to use it since the design is already really good in portrait and i dont see how landscape could improve it. 

PR disabling landscape will hit next week.
