### ISSUE TITLE
The third button on the dice setting has a string crop out. It should be "D20", I believe.

### ISSUE THREAD

**Issue by n-apps** [n-apps/ScoreCounter#68]
Device: Galaxy S8
OS: Android 9
Screen Resolution: 1480×720
Minimum width set in developers settings: 360dp (default)

<img src="https://user-images.githubusercontent.com/16646251/93013060-b69b4d80-f5ad-11ea-9cb9-2d99d634038d.png" width="250">

**Comment by vabene1111** [comment]
i have tried changing the `android:elipsize` https://developer.android.com/reference/android/widget/TextView#attr_android:ellipsize property but it does not seem to have an effect on the buttons. I have also tried to change the paddings to the right and left of the text boxes to be a little smaller but it did not have an effect either (my android skills are a little rusty i guess). 

One simple solution would be to use a little smaller margin to the right and left of the selection as shown in the screenshot below (left original, right smaller margin). There might still be devices where even this is to small but they will probably require a completly different solution.

![image](https://user-images.githubusercontent.com/6819595/94256272-dd507100-ff29-11ea-8d01-e55b33f673cd.png)

if you like the change i will open a PR next week

**Comment by n-apps** [comment]
> (my android skills are a little rusty i guess).
nope, this is widget from fresh Google lib, so everything can be broken (I literally issued a bug seconds ago) :)

I like solution with margins 👍‍‍
