### ISSUE TITLE
Use a unique color when adding a new counter

### ISSUE THREAD

**Issue by n-apps** [n-apps/ScoreCounter#7]
Rewrite or improve logic which chooses color for new counters. Colors of the side by side placed counters should be different. Problem is when you add new counter after you have removed any counter (but not the last one).

**Comment by matthias1700** [comment]
Hello, I will be grateful if I could work on it. Is this task still free?? If you have some specific requirements, feel free to write it. I am not very experienced but this task sound good for me.

**Comment by matthias1700** [comment]
Ok, I´ll do this. In case of any question, I´ll write you.

**Comment by matthias1700** [comment]
Hello man, I am done with this isssue. Tomorrow I will create pull request. I will do more tests before pull request.

**Comment by matthias1700** [comment]
Hello, 
I sent pull request 10 days ago so I am just remembrenig that task is done. 
Please, check it.

**Comment by n-apps** [comment]
Released in 4.4.0
