### ISSUE TITLE
Custom font doesn't support latin special characters

### ISSUE THREAD

**Issue by GustavoHGAraujo** [n-apps/ScoreCounter#80]
The font Butik Sans don't have support for latin special characters like `ç`. `á`, `ã`. When using some latin names, the text appears with two different fonts (Roboto and Butik Sans).

This issue will affect the future latin languages translations.

<img width="300px" src="https://user-images.githubusercontent.com/18123187/147861701-ec777511-2763-41c3-a51a-fa2e2229cca5.png" />

**Comment by n-apps** [comment]
Thanks for contributing! Font has been replaced in v 6.9.6

![Screenshot_1641414366](https://user-images.githubusercontent.com/16646251/148284348-b8cd5abe-178c-4f83-9dc0-8b718dca7914.png)
