### ISSUE TITLE
Previous die roll shows wrong value

### ISSUE THREAD

**Issue by zmarties** [n-apps/ScoreCounter#84]
When you roll a die, the screen is supposed to show the previous roll as text below the current one.

However this does not happen for the first roll after switching back to the die panel if you have used it before. The text is there, and a number shown, but when you roll again, the number below stays the same, and the die rolls to a new number.

On subsequent rolls, the displayed value does move to the previous value, so it just looks like you are failing to update the history properly when you switch back to the die panel.

**Comment by n-apps** [comment]
Fixed (presumably) in v7.0.5. Thanks for spotting it!
